package md.social.filemanager.dto;

public enum NotificationType
{
    FILE_UPLOAD_SUCCESS,
    FILE_UPLOAD_FAILURE,
    FILE_DELETION_SUCCESS,
    FILE_DELETION_FAILURE,
    FILE_DOWNLOAD_SUCCESS,
    FILE_DOWNLOAD_FAILURE,
    FILE_SHARED,
    FILE_PERMISSION_CHANGED,
    STORAGE_LIMIT_REACHED,
    FILE_RENAMED
}
